[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://vidsrc.to https://vidsrc.cc https://mxdrop.sx https://www.youtube.com https://blogspot.com"
    Content-Security-Policy = "frame-src 'self' https://vidsrc.to https://vidsrc.cc https://mxdrop.sx https://www.youtube.com https://www.youtube-nocookie.com https://blogspot.com https://*.blogspot.com;"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
